### ISSUE TITLE
Remove Instructions for Adding OBO File

### ISSUE THREAD

**Issue by DarioS** [rpeckner-broad/Specter#1]
Recently, pymzml 2 is released and the adding of an OBO file is no longer necessary. The instructions could be removed from the user guide. Also, valid syntax for the `mem` option could be defined.

**Comment by rpeckner-broad** [comment]
Unfortunately, as far as I can tell pymzml2 is not backwards compatible with python2, and I don't intend to migrate Specter to python3 in the foreseeable future. Appropriate syntax for the `mem` option is illustrated in the example in the user guide: <# desired GB>g.
