### ISSUE TITLE
"Error in if (IsThereEnoughData[k]) { : argument is of length zero"

### ISSUE THREAD

**Issue by MaxAlex** [rpeckner-broad/Specter#11]
I'm trying to apply Specter to the results of an experiment performed using a Thermo instrument (so, on an mzML file derived from a .RAW-format file via MSConvert) that was searched via Mascot (so I have a .blib spectral database created by BiblioSpec's BlibBuild.exe from a Mascot .dat search result file), running on Ubuntu Linux using Python 2.7.

Running SpecterStandalone.sh on the files, the Python script segment runs (apparently) successfully and generates a "SpecterResults" directory containing three .csvs ('...header.csv', 'SpecterCoeffs.csv', and 'SpecterCoeffsDecoys.csv'), each about ~200 KB.  However, the R script segment fails, showing the following:

```
Loading required package: kza
Loading required package: pracma
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: moments
Error in if (IsThereEnoughData[k]) { : argument is of length zero
Calls: QuantifyAllFromSpecterCoeffs -> Map -> mapply -> <Anonymous>
Execution halted
```

Any ideas what is going on here, or further steps to diagnose?  Thanks!

**Comment by MaxAlex** [comment]
Poking around a bit further- it looks like the underlying issue is that all the values in columns 3 to 6 of ...SpecterCoeffs.csv are all zero in all rows, so all rows get filtered out.  The ...SpecterCoeffsDecoys.csv file has the same issue.

Is this indicating that Specter isn't finding anything in my data?

**Comment by rpeckner-broad** [comment]
Hi Max,
It definitely looks like Specter isn't finding anything in your data. There
are a couple of possible reasons for this. The default mass accuracy
parameter is 10 ppm, which might not be appropriate for your data and can
dramatically effect the results. Also, I noticed that you said the data
were searched by Mascot - make sure that the mzML you give Specter is
derived from a DIA experiment and not the DDA runs you use to build the
library. Finally, the raw data needs to be centroided when converted to
mzML. If none of those possibilities fixes the problem I can take a closer
look at your issue.
Thanks,
Ryan

**Comment by MaxAlex** [comment]
I've tried several tolerance values (up to 1000ppm, which should be far too wide), the data is centroided, and the mzML file is from a DIA run (however it might not be the right kind of DIA run, see below.)

Running in debug mode, I find that `MaxOffset` always winds up being set to 0 (at line 388.)  Also, MaxWindowPrecMZ winds up being set too low (at the precise value of the precursor in the mzML file,) causing the entire SpectraLibrary to be filtered out (the precursor MZ values in the library are all slightly above the precursor values from the mzML file, due to the width of the acquisition window.)  When I set both of these values manually, I get nonzero results from the Python script and the process completes successfully (I'm not sure they're correct results, due to the arbitrarily chosen values, but a ...SpecterQuants.csv file is generated.)

Both of these seem to be set by looking at differences in the precursor MZ between scans (if I'm reading line 367 correctly.)  The file I'm trying to analyze, however, is a DIA run over one precursor MZ (to look at phosphorylation site assignment(s) on a single peptide) so the difference between MS2 precursors is always zero, leading to the 0-width window values noted above.  Is there a way to run Specter on this kind of data?

Thanks again!

**Comment by rpeckner-broad** [comment]
Hi Max,
I've modified Specter_Standalone.py to account for your situation, by letting you specify the width of your single m/z window as the last argument at the command line (after the ppm tolerance). I haven't tested the change so let me know if you encounter a problem.

**Comment by MaxAlex** [comment]
That works!  Thanks for your help.
