### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by courcelm** [rpeckner-broad/Specter#13]
Hello,

I'm having the following issue with Specter :

Command:

(SpecterEnv) mathieu@tyersub3-iric:/mnt/projects/MC2018-06-14/Specter$ ./SpecterStandalone.sh /mnt/ms/QEXACTIVE_HF/MAY22_2018/Syn_peptidemix_3_6 /mnt/ms/QEXACTIVE_HF/MAY22_2018/lib 14000 end 8 orbitrap 10

Log:

Library loaded in 0.0 minutes
Loaded 4078 MS2 spectra from /mnt/ms/QEXACTIVE_HF/MAY22_2018/Syn_peptidemix_3_6.mzML in 0.5 minutes.
Header written to /mnt/ms/QEXACTIVE_HF/MAY22_2018/SpecterResults/Syn_peptidemix_3_6_lib_header.csv.
Analyzing MS2 spectra:
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4077/4077 [00:04<00:00, 879.76it/s]
Output written to /mnt/ms/QEXACTIVE_HF/MAY22_2018/SpecterResults/Syn_peptidemix_3_6_lib_SpecterCoeffs.csv.
Analyzing MS2 spectra with decoys:
  0%|                                                                                                                                                                                          | 0/4077 [00:00<?, ?it/s]Traceback (most recent call last):
  File "Specter_Standalone.py", line 420, in <module>
    output = list(tqdm.tqdm(p.imap(partial(RegressSpectraOntoLibraryWithDecoys,Library=SpectraLibrary,tol=delta*1e-6,maxWindowOffset=MaxOffset), res), total=len(res)))
  File "/home/mathieu/code/miniconda3/envs/SpecterEnv/lib/python2.7/site-packages/tqdm/_tqdm.py", line 941, in __iter__
    for obj in iterable:
  File "/home/mathieu/code/miniconda3/envs/SpecterEnv/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: 'numpy.float64' object cannot be interpreted as an index
Exception KeyError: KeyError(<weakref at 0x7f219bad2470; to 'tqdm' at 0x7f2196fde110>,) in <bound method tqdm.__del__ of   0%|                                                                                                                                                                                          | 0/4077 [00:00<?, ?it/s]> ignored
Error in file(file, "rt") : cannot open the connection
Calls: SparkSpecterCoeffs -> read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/mnt/ms/QEXACTIVE_HF/MAY22_2018/SpecterResults/Syn_peptidemix_3_6_lib_SpecterCoeffsDecoys.csv': No such file or directory
Execution halted

**Comment by rpeckner-broad** [comment]
This looks like it's a problem with index interpretation in recent versions of numpy (see https://github.com/rbgirshick/py-faster-rcnn/issues/481). If you don't mind potentially downgrading your numpy version, you can try `sudo pip install -U numpy==1.11.0` and run the job again. Meanwhile, I'll try to debug the point at which a float is being passed as an integer index.

**Comment by courcelm** [comment]
Same issue with numpy 1.11.0

**Comment by courcelm** [comment]
I refreshed my env with:
conda env update -f SpecterEnv.yml

and its now working. Thanks for your assistance!
