### ISSUE TITLE
TraML Format Support

### ISSUE THREAD

**Issue by DarioS** [rpeckner-broad/Specter#2]
The software would be more flexible if it didn't depend on Skyline's Blib format. Skyline is Windows-only software, whereas a format such as TraML is HUPO-endorsed and cross-platform.

**Comment by rpeckner-broad** [comment]
Blibs can be generated from outside of Skyline using the cross-platform command-line tool BiblioSpec, a part of the ProteoWizard project: https://skyline.ms/project/home/software/BiblioSpec/begin.view.
