### ISSUE TITLE
cloud framework

### ISSUE THREAD

**Issue by tobiasko** [rpeckner-broad/Specter#5]
"Specter currently requires the cluster-computing framework Apache Spark; a cloud framework and accompanying website will appear in the future."

The dependency on Spark is def. a big drawback if people would like to test Specter using their own data. Can you estimate when the cloud framework will be ready and released to the public?

Greetings,
Tobi

**Comment by DarioS** [comment]
I would like to have the option of executing a standalone version. The research group which I am a part of has a server with 48 CPUs and 512 GB RAM. The operating system running it is Debian 9. I don't understand the benefit of Apache Spark nor of cloud computing since I wouldn't need to use multiple computers to do an analysis. I'm not a Python programmer, but I presume that Python has a simple parallel processing framework like R's `parallel` package.

**Comment by rpeckner-broad** [comment]
Spark doesn't necessarily need to run in a cloud computing environment; it can also run locally and in standalone mode as described [here](https://spark.apache.org/docs/latest/spark-standalone.html). That said, I'm working on a "desktop" version of Specter that can run without Spark, using Python's multiprocessing capacity as you mention, and I'll update this thread when it's ready. It will be far slower on a local machine without Spark, but with the server you're describing it should perform comparably.

**Comment by rpeckner-broad** [comment]
I've added the scripts to allow Specter to run in standalone mode; see the SpecterStandaloneUserGuide.pdf for details. Let me know if you have trouble getting it to work on your system.
Thanks,
Ryan

**Comment by DarioS** [comment]
I got to the end of the analysis using some of your data and experienced an error.

```
$ ./SpecterStandalone.sh ~/SpecterTest/CC20170118_SAM_Specter_Ecolidigest_DDA_01 ~/SpecterTest/EcoliSpectralLibrary 1000 end 12
Library loaded in 2.0 minutes
Loaded 534 MS2 spectra from /home/dario/SpecterTest/CC20170118_SAM_Specter_Ecolidigest_DDA_01.mzML in 1.2 minutes.
Header written to /home/dario/SpecterTest/SpecterResults/CC20170118_SAM_Specter_Ecolidigest_DDA_01_EcoliSpectralLibrary_header.csv.
100%  533/533 [02:34<00:00,  3.45it/s]
Traceback (most recent call last):
  File "Specter_Standalone.py", line 391, in <module>
    output = [p.get() for p in results]
AttributeError: 'list' object has no attribute 'get'
Error in file(file, "rt") : cannot open the connection
Calls: SparkSpecterCoeffs -> read.csv -> read.table -> file
```

Is there some configuration which I haven't done?

**Comment by rpeckner-broad** [comment]
Sorry, this was a bug in the standalone version. I've updated it and the error should be fixed.
